---

- name: apt cache is up-to-date.
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 7200

- name: apt itself is up-to-date.
  become: yes
  apt:
    name: aptitude
    state: latest

- name: upgrade programs installed via apt.
  become: yes
  apt:
    upgrade: yes
